[platformio]
default_envs = esp32s3_xiao_sense

[env]
platform = espressif32
framework = arduino
monitor_speed = 115200
upload_speed = 921600
build_flags =
  -DCORE_DEBUG_LEVEL=1
  -DCOFFEE_CAM_AP_SSID=\"coffee-station-cam\"
  -DCOFFEE_CAM_AP_PASSWORD=\"coffeecam\"
  -DCOFFEE_CAM_MDNS=\"esp32cam\"

[env:esp32s3_xiao_sense]
board = seeed_xiao_esp32s3
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_upload.flash_size = 8MB
build_flags =
  ${env.build_flags}
  -DBOARD_HAS_PSRAM
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DCAMERA_MODEL_XIAO_ESP32S3

[env:esp32s3_eye]
board = esp32-s3-devkitc-1
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_upload.flash_size = 8MB
build_flags =
  ${env.build_flags}
  -DBOARD_HAS_PSRAM
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DCAMERA_MODEL_ESP32S3_EYE

[env:ai_thinker_esp32_cam]
board = esp32cam
build_flags =
  ${env.build_flags}
  -DBOARD_HAS_PSRAM
  -DCAMERA_MODEL_AI_THINKER
